code = 689:WY
phillipsbench
SNOTEL csv has no snowdepth for this run
forcing file created, now running summa
Model status: Success
number of crust days:25.208333333333332
summa run for phillipsbench_current_WY00 complete, check output folder for output file
SNOTEL csv has no snowdepth for this run
forcing file created, now running summa
Model status: Success
number of crust days:115.125
summa run for phillipsbench_current_WY01 complete, check output folder for output file
SNOTEL csv has no snowdepth for this run
forcing file created, now running summa
Model status: Success
number of crust days:131.5
summa run for phillipsbench_current_WY02 complete, check output folder for output file
SNOTEL csv has no snowdepth for this run
forcing file created, now running summa
Model status: Success
number of crust days:27.958333333333332
summa run for phillipsbench_current_WY03 complete, check output folder for output file
SNOTEL csv has no snowdepth for this run
forcing file created, now running summa
Model status: Success
number of crust days:26.0
summa run for phillipsbench_current_WY04 complete, check output folder for output file
SNOTEL csv has no snowdepth for this run
forcing file created, now running summa
Model status: Success
number of crust days:36.541666666666664
summa run for phillipsbench_current_WY05 complete, check output folder for output file
SNOTEL csv has no snowdepth for this run
forcing file created, now running summa
Model status: Success
number of crust days:6.5
summa run for phillipsbench_current_WY06 complete, check output folder for output file
SNOTEL csv has no snowdepth for this run
forcing file created, now running summa
Model status: Success
number of crust days:50.666666666666664
summa run for phillipsbench_current_WY07 complete, check output folder for output file
SNOTEL csv has no snowdepth for this run
forcing file created, now running summa
Model status: Success
number of crust days:47.791666666666664
summa run for phillipsbench_current_WY08 complete, check output folder for output file
SNOTEL csv has no snowdepth for this run
forcing file created, now running summa
Model status: Success
number of crust days:18.666666666666668
summa run for phillipsbench_current_WY09 complete, check output folder for output file
SNOTEL csv has no snowdepth for this run
forcing file created, now running summa
Model status: Success
number of crust days:56.166666666666664
summa run for phillipsbench_current_WY10 complete, check output folder for output file
SNOTEL csv has no snowdepth for this run
forcing file created, now running summa
Model status: Success
number of crust days:21.375
summa run for phillipsbench_current_WY11 complete, check output folder for output file
SNOTEL csv has no snowdepth for this run
forcing file created, now running summa
Model status: Success
number of crust days:34.791666666666664
summa run for phillipsbench_current_WY12 complete, check output folder for output file
SNOTEL csv has no snowdepth for this run
forcing file created, now running summa
Model status: Success
number of crust days:41.583333333333336
summa run for phillipsbench_current_WY13 complete, check output folder for output file
SNOTEL csv has no snowdepth for this run
forcing file created, now running summa
Model status: Success
number of crust days:13.375
summa run for phillipsbench_current_WY14 complete, check output folder for output file
SNOTEL csv has no snowdepth for this run
forcing file created, now running summa
Model status: Success
number of crust days:29.0
summa run for phillipsbench_current_WY15 complete, check output folder for output file
SNOTEL csv has no snowdepth for this run
forcing file created, now running summa
Model status: Success
number of crust days:18.166666666666668
summa run for phillipsbench_current_WY16 complete, check output folder for output file
SNOTEL csv has no snowdepth for this run
forcing file created, now running summa
Model status: Success
number of crust days:59.791666666666664
summa run for phillipsbench_current_WY17 complete, check output folder for output file
SNOTEL csv has no snowdepth for this run
forcing file created, now running summa
Model status: Success
number of crust days:45.875
summa run for phillipsbench_current_WY18 complete, check output folder for output file
SNOTEL csv has no snowdepth for this run
forcing file created, now running summa
Model status: Success
number of crust days:37.791666666666664
summa run for phillipsbench_current_WY19 complete, check output folder for output file
SNOTEL csv has no snowdepth for this run
forcing file created, now running summa
Model status: Success
number of crust days:36.958333333333336
summa run for phillipsbench_current_WY20 complete, check output folder for output file
SNOTEL csv has no snowdepth for this run
forcing file created, now running summa
Model status: Success
number of crust days:46.208333333333336
summa run for phillipsbench_current_WY21 complete, check output folder for output file
SNOTEL csv has no snowdepth for this run
forcing file created, now running summa
Model status: Success
number of crust days:53.416666666666664
summa run for phillipsbench_current_WY22 complete, check output folder for output file
SNOTEL csv has no snowdepth for this run
forcing file created, now running summa
Model status: Success
number of crust days:15.708333333333334
summa run for phillipsbench_current_WY23 complete, check output folder for output file
SNOTEL csv has no snowdepth for this run
forcing file created, now running summa
Model status: Success
number of crust days:88.79166666666667
summa run for phillipsbench_current_WY24 complete, check output folder for output file
Enter the desired SNOTEL site code (ie. 1107:WA): Enter the water year: Enter the output file name (ie. buck_WY16): No SNOWDEPTH found for MyStation
********** generating the forcing file, please be patient **********
********** should take ~3 minutes to run **********
SNOTEL csv has no snowdepth for this run
forcing file created, now running summa
Model status: Success
number of crust days:54.416666666666664
summa run for phillipsbench_+2K_WY00 complete, check output folder for output file
Enter the desired SNOTEL site code (ie. 1107:WA): Enter the water year: Enter the output file name (ie. buck_WY16): No SNOWDEPTH found for MyStation
********** generating the forcing file, please be patient **********
********** should take ~3 minutes to run **********
SNOTEL csv has no snowdepth for this run
forcing file created, now running summa
Model status: Success
number of crust days:71.0
summa run for phillipsbench_+2K_WY01 complete, check output folder for output file
Enter the desired SNOTEL site code (ie. 1107:WA): Enter the water year: Enter the output file name (ie. buck_WY16): ********** generating the forcing file, please be patient **********
********** should take ~3 minutes to run **********
forcing file created, now running summa
Model status: Success
number of crust days:21.25
summa run for phillipsbench_+2K_WY02 complete, check output folder for output file
Enter the desired SNOTEL site code (ie. 1107:WA): Enter the water year: Enter the output file name (ie. buck_WY16): ********** generating the forcing file, please be patient **********
********** should take ~3 minutes to run **********
forcing file created, now running summa
Model status: Success
number of crust days:55.708333333333336
summa run for phillipsbench_+2K_WY03 complete, check output folder for output file
Enter the desired SNOTEL site code (ie. 1107:WA): Enter the water year: Enter the output file name (ie. buck_WY16): ********** generating the forcing file, please be patient **********
********** should take ~3 minutes to run **********
forcing file created, now running summa
Model status: Success
number of crust days:14.166666666666666
summa run for phillipsbench_+2K_WY04 complete, check output folder for output file
Enter the desired SNOTEL site code (ie. 1107:WA): Enter the water year: Enter the output file name (ie. buck_WY16): ********** generating the forcing file, please be patient **********
********** should take ~3 minutes to run **********
forcing file created, now running summa
Model status: Success
number of crust days:58.916666666666664
summa run for phillipsbench_+2K_WY05 complete, check output folder for output file
Enter the desired SNOTEL site code (ie. 1107:WA): Enter the water year: Enter the output file name (ie. buck_WY16): ********** generating the forcing file, please be patient **********
********** should take ~3 minutes to run **********
forcing file created, now running summa
Model status: Success
number of crust days:27.0
summa run for phillipsbench_+2K_WY06 complete, check output folder for output file
Enter the desired SNOTEL site code (ie. 1107:WA): Enter the water year: Enter the output file name (ie. buck_WY16): ********** generating the forcing file, please be patient **********
********** should take ~3 minutes to run **********
forcing file created, now running summa
Model status: Success
number of crust days:35.208333333333336
summa run for phillipsbench_+2K_WY07 complete, check output folder for output file
Enter the desired SNOTEL site code (ie. 1107:WA): Enter the water year: Enter the output file name (ie. buck_WY16): ********** generating the forcing file, please be patient **********
********** should take ~3 minutes to run **********
forcing file created, now running summa
Model status: Success
number of crust days:68.5
summa run for phillipsbench_+2K_WY08 complete, check output folder for output file
Enter the desired SNOTEL site code (ie. 1107:WA): Enter the water year: Enter the output file name (ie. buck_WY16): ********** generating the forcing file, please be patient **********
********** should take ~3 minutes to run **********
forcing file created, now running summa
Model status: Success
number of crust days:47.416666666666664
summa run for phillipsbench_+2K_WY09 complete, check output folder for output file
Enter the desired SNOTEL site code (ie. 1107:WA): Enter the water year: Enter the output file name (ie. buck_WY16): ********** generating the forcing file, please be patient **********
********** should take ~3 minutes to run **********
forcing file created, now running summa
Model status: Success
number of crust days:71.91666666666667
summa run for phillipsbench_+2K_WY10 complete, check output folder for output file
Enter the desired SNOTEL site code (ie. 1107:WA): Enter the water year: Enter the output file name (ie. buck_WY16): ********** generating the forcing file, please be patient **********
********** should take ~3 minutes to run **********
forcing file created, now running summa
Model status: Success
number of crust days:76.375
summa run for phillipsbench_+2K_WY11 complete, check output folder for output file
Enter the desired SNOTEL site code (ie. 1107:WA): Enter the water year: Enter the output file name (ie. buck_WY16): ********** generating the forcing file, please be patient **********
********** should take ~3 minutes to run **********
forcing file created, now running summa
Model status: Success
number of crust days:56.458333333333336
summa run for phillipsbench_+2K_WY12 complete, check output folder for output file
Enter the desired SNOTEL site code (ie. 1107:WA): Enter the water year: Enter the output file name (ie. buck_WY16): ********** generating the forcing file, please be patient **********
********** should take ~3 minutes to run **********
forcing file created, now running summa
Model status: Success
number of crust days:124.875
summa run for phillipsbench_+2K_WY13 complete, check output folder for output file
Enter the desired SNOTEL site code (ie. 1107:WA): Enter the water year: Enter the output file name (ie. buck_WY16): ********** generating the forcing file, please be patient **********
********** should take ~3 minutes to run **********
forcing file created, now running summa
Model status: Success
number of crust days:36.833333333333336
summa run for phillipsbench_+2K_WY14 complete, check output folder for output file
Enter the desired SNOTEL site code (ie. 1107:WA): Enter the water year: Enter the output file name (ie. buck_WY16): ********** generating the forcing file, please be patient **********
********** should take ~3 minutes to run **********
forcing file created, now running summa
Model status: Success
number of crust days:106.75
summa run for phillipsbench_+2K_WY15 complete, check output folder for output file
Enter the desired SNOTEL site code (ie. 1107:WA): Enter the water year: Enter the output file name (ie. buck_WY16): ********** generating the forcing file, please be patient **********
********** should take ~3 minutes to run **********
forcing file created, now running summa
Model status: Success
number of crust days:38.916666666666664
summa run for phillipsbench_+2K_WY16 complete, check output folder for output file
Enter the desired SNOTEL site code (ie. 1107:WA): Enter the water year: Enter the output file name (ie. buck_WY16): ********** generating the forcing file, please be patient **********
********** should take ~3 minutes to run **********
forcing file created, now running summa
Model status: Success
number of crust days:62.333333333333336
summa run for phillipsbench_+2K_WY17 complete, check output folder for output file
Enter the desired SNOTEL site code (ie. 1107:WA): Enter the water year: Enter the output file name (ie. buck_WY16): ********** generating the forcing file, please be patient **********
********** should take ~3 minutes to run **********
forcing file created, now running summa
Model status: Success
number of crust days:85.75
summa run for phillipsbench_+2K_WY18 complete, check output folder for output file
Enter the desired SNOTEL site code (ie. 1107:WA): Enter the water year: Enter the output file name (ie. buck_WY16): ********** generating the forcing file, please be patient **********
********** should take ~3 minutes to run **********
forcing file created, now running summa
Model status: Success
number of crust days:15.041666666666666
summa run for phillipsbench_+2K_WY19 complete, check output folder for output file
Enter the desired SNOTEL site code (ie. 1107:WA): Enter the water year: Enter the output file name (ie. buck_WY16): ********** generating the forcing file, please be patient **********
********** should take ~3 minutes to run **********
forcing file created, now running summa
Model status: Success
number of crust days:49.916666666666664
summa run for phillipsbench_+2K_WY20 complete, check output folder for output file
Enter the desired SNOTEL site code (ie. 1107:WA): Enter the water year: Enter the output file name (ie. buck_WY16): ********** generating the forcing file, please be patient **********
********** should take ~3 minutes to run **********
forcing file created, now running summa
Model status: Success
number of crust days:47.708333333333336
summa run for phillipsbench_+2K_WY21 complete, check output folder for output file
Enter the desired SNOTEL site code (ie. 1107:WA): Enter the water year: Enter the output file name (ie. buck_WY16): ********** generating the forcing file, please be patient **********
********** should take ~3 minutes to run **********
forcing file created, now running summa
Model status: Success
number of crust days:71.875
summa run for phillipsbench_+2K_WY22 complete, check output folder for output file
Enter the desired SNOTEL site code (ie. 1107:WA): Enter the water year: Enter the output file name (ie. buck_WY16): ********** generating the forcing file, please be patient **********
********** should take ~3 minutes to run **********
forcing file created, now running summa
Model status: Success
number of crust days:21.833333333333332
summa run for phillipsbench_+2K_WY23 complete, check output folder for output file
Enter the desired SNOTEL site code (ie. 1107:WA): Enter the water year: Enter the output file name (ie. buck_WY16): ********** generating the forcing file, please be patient **********
********** should take ~3 minutes to run **********
forcing file created, now running summa
Model status: Success
number of crust days:49.041666666666664
summa run for phillipsbench_+2K_WY24 complete, check output folder for output file
Enter the desired SNOTEL site code (ie. 1107:WA): Enter the water year: Enter the output file name (ie. buck_WY16): No SNOWDEPTH found for MyStation
********** generating the forcing file, please be patient **********
********** should take ~3 minutes to run **********
SNOTEL csv has no snowdepth for this run
forcing file created, now running summa
Model status: Success
number of crust days:95.58333333333333
summa run for phillipsbench_+4K_WY00 complete, check output folder for output file
Enter the desired SNOTEL site code (ie. 1107:WA): Enter the water year: Enter the output file name (ie. buck_WY16): No SNOWDEPTH found for MyStation
********** generating the forcing file, please be patient **********
********** should take ~3 minutes to run **********
SNOTEL csv has no snowdepth for this run
forcing file created, now running summa
Model status: Success
number of crust days:51.916666666666664
summa run for phillipsbench_+4K_WY01 complete, check output folder for output file
Enter the desired SNOTEL site code (ie. 1107:WA): Enter the water year: Enter the output file name (ie. buck_WY16): ********** generating the forcing file, please be patient **********
********** should take ~3 minutes to run **********
forcing file created, now running summa
Model status: Success
number of crust days:42.75
summa run for phillipsbench_+4K_WY02 complete, check output folder for output file
Enter the desired SNOTEL site code (ie. 1107:WA): Enter the water year: Enter the output file name (ie. buck_WY16): ********** generating the forcing file, please be patient **********
********** should take ~3 minutes to run **********
forcing file created, now running summa
Model status: Success
number of crust days:57.875
summa run for phillipsbench_+4K_WY03 complete, check output folder for output file
Enter the desired SNOTEL site code (ie. 1107:WA): Enter the water year: Enter the output file name (ie. buck_WY16): ********** generating the forcing file, please be patient **********
********** should take ~3 minutes to run **********
forcing file created, now running summa
Model status: Success
number of crust days:49.833333333333336
summa run for phillipsbench_+4K_WY04 complete, check output folder for output file
Enter the desired SNOTEL site code (ie. 1107:WA): Enter the water year: Enter the output file name (ie. buck_WY16): ********** generating the forcing file, please be patient **********
********** should take ~3 minutes to run **********
forcing file created, now running summa
Model status: Success
number of crust days:78.875
summa run for phillipsbench_+4K_WY05 complete, check output folder for output file
Enter the desired SNOTEL site code (ie. 1107:WA): Enter the water year: Enter the output file name (ie. buck_WY16): ********** generating the forcing file, please be patient **********
********** should take ~3 minutes to run **********
forcing file created, now running summa
Model status: Success
number of crust days:84.79166666666667
summa run for phillipsbench_+4K_WY06 complete, check output folder for output file
Enter the desired SNOTEL site code (ie. 1107:WA): Enter the water year: Enter the output file name (ie. buck_WY16): ********** generating the forcing file, please be patient **********
********** should take ~3 minutes to run **********
forcing file created, now running summa
Model status: Success
number of crust days:49.166666666666664
summa run for phillipsbench_+4K_WY07 complete, check output folder for output file
Enter the desired SNOTEL site code (ie. 1107:WA): Enter the water year: Enter the output file name (ie. buck_WY16): ********** generating the forcing file, please be patient **********
********** should take ~3 minutes to run **********
forcing file created, now running summa
Model status: Success
number of crust days:69.91666666666667
summa run for phillipsbench_+4K_WY08 complete, check output folder for output file
Enter the desired SNOTEL site code (ie. 1107:WA): Enter the water year: Enter the output file name (ie. buck_WY16): ********** generating the forcing file, please be patient **********
********** should take ~3 minutes to run **********
forcing file created, now running summa
Model status: Success
number of crust days:86.79166666666667
summa run for phillipsbench_+4K_WY09 complete, check output folder for output file
Enter the desired SNOTEL site code (ie. 1107:WA): Enter the water year: Enter the output file name (ie. buck_WY16): ********** generating the forcing file, please be patient **********
********** should take ~3 minutes to run **********
forcing file created, now running summa
Model status: Success
number of crust days:74.70833333333333
summa run for phillipsbench_+4K_WY10 complete, check output folder for output file
Enter the desired SNOTEL site code (ie. 1107:WA): Enter the water year: Enter the output file name (ie. buck_WY16): ********** generating the forcing file, please be patient **********
********** should take ~3 minutes to run **********
forcing file created, now running summa
Model status: Success
number of crust days:92.70833333333333
summa run for phillipsbench_+4K_WY11 complete, check output folder for output file
Enter the desired SNOTEL site code (ie. 1107:WA): Enter the water year: Enter the output file name (ie. buck_WY16): ********** generating the forcing file, please be patient **********
********** should take ~3 minutes to run **********
forcing file created, now running summa
Model status: Success
number of crust days:90.875
summa run for phillipsbench_+4K_WY12 complete, check output folder for output file
Enter the desired SNOTEL site code (ie. 1107:WA): Enter the water year: Enter the output file name (ie. buck_WY16): ********** generating the forcing file, please be patient **********
********** should take ~3 minutes to run **********
forcing file created, now running summa
Model status: Success
number of crust days:54.333333333333336
summa run for phillipsbench_+4K_WY13 complete, check output folder for output file
Enter the desired SNOTEL site code (ie. 1107:WA): Enter the water year: Enter the output file name (ie. buck_WY16): ********** generating the forcing file, please be patient **********
********** should take ~3 minutes to run **********
forcing file created, now running summa
Model status: Success
number of crust days:51.666666666666664
summa run for phillipsbench_+4K_WY14 complete, check output folder for output file
Enter the desired SNOTEL site code (ie. 1107:WA): Enter the water year: Enter the output file name (ie. buck_WY16): ********** generating the forcing file, please be patient **********
********** should take ~3 minutes to run **********
forcing file created, now running summa
Model status: Success
number of crust days:41.041666666666664
summa run for phillipsbench_+4K_WY15 complete, check output folder for output file
Enter the desired SNOTEL site code (ie. 1107:WA): Enter the water year: Enter the output file name (ie. buck_WY16): ********** generating the forcing file, please be patient **********
********** should take ~3 minutes to run **********
forcing file created, now running summa
Model status: Success
number of crust days:33.541666666666664
summa run for phillipsbench_+4K_WY16 complete, check output folder for output file
Enter the desired SNOTEL site code (ie. 1107:WA): Enter the water year: Enter the output file name (ie. buck_WY16): ********** generating the forcing file, please be patient **********
********** should take ~3 minutes to run **********
forcing file created, now running summa
Model status: Success
number of crust days:45.041666666666664
summa run for phillipsbench_+4K_WY17 complete, check output folder for output file
Enter the desired SNOTEL site code (ie. 1107:WA): Enter the water year: Enter the output file name (ie. buck_WY16): ********** generating the forcing file, please be patient **********
********** should take ~3 minutes to run **********
forcing file created, now running summa
Model status: Success
number of crust days:68.41666666666667
summa run for phillipsbench_+4K_WY18 complete, check output folder for output file
Enter the desired SNOTEL site code (ie. 1107:WA): Enter the water year: Enter the output file name (ie. buck_WY16): ********** generating the forcing file, please be patient **********
********** should take ~3 minutes to run **********
forcing file created, now running summa
Model status: Success
number of crust days:73.83333333333333
summa run for phillipsbench_+4K_WY19 complete, check output folder for output file
Enter the desired SNOTEL site code (ie. 1107:WA): Enter the water year: Enter the output file name (ie. buck_WY16): ********** generating the forcing file, please be patient **********
********** should take ~3 minutes to run **********
forcing file created, now running summa
Model status: Success
number of crust days:57.416666666666664
summa run for phillipsbench_+4K_WY20 complete, check output folder for output file
Enter the desired SNOTEL site code (ie. 1107:WA): Enter the water year: Enter the output file name (ie. buck_WY16): ********** generating the forcing file, please be patient **********
********** should take ~3 minutes to run **********
forcing file created, now running summa
Model status: Success
number of crust days:39.625
summa run for phillipsbench_+4K_WY21 complete, check output folder for output file
Enter the desired SNOTEL site code (ie. 1107:WA): Enter the water year: Enter the output file name (ie. buck_WY16): ********** generating the forcing file, please be patient **********
********** should take ~3 minutes to run **********
forcing file created, now running summa
Model status: Success
number of crust days:79.625
summa run for phillipsbench_+4K_WY22 complete, check output folder for output file
Enter the desired SNOTEL site code (ie. 1107:WA): Enter the water year: Enter the output file name (ie. buck_WY16): ********** generating the forcing file, please be patient **********
********** should take ~3 minutes to run **********
forcing file created, now running summa
Model status: Success
number of crust days:114.66666666666667
summa run for phillipsbench_+4K_WY23 complete, check output folder for output file
Enter the desired SNOTEL site code (ie. 1107:WA): Enter the water year: Enter the output file name (ie. buck_WY16): ********** generating the forcing file, please be patient **********
********** should take ~3 minutes to run **********
forcing file created, now running summa
Model status: Success
number of crust days:68.5
summa run for phillipsbench_+4K_WY24 complete, check output folder for output file
code = 1082:WY
grandtarghee
No ACCUMULATED PRECIPITATION found for MyStation
No AIR TEMP found for MyStation
Traceback (most recent call last):
  File "/home/cdalden/summa_setup/model/snotel_to_pysumma_current.py", line 111, in <module>
    df.reset_index(inplace=True)
AttributeError: 'NoneType' object has no attribute 'reset_index'
forcing file created, now running summa
Traceback (most recent call last):
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/file_manager.py", line 211, in _acquire_with_cache_info
    file = self._cache[self._key]
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/lru_cache.py", line 56, in __getitem__
    value = self._cache[key]
KeyError: [<class 'netCDF4._netCDF4.Dataset'>, ('/home/cdalden/summa_setup/model/forcings/grandtarghee_current_WY00.nc',), 'r', (('clobber', True), ('diskless', False), ('format', 'NETCDF4'), ('persist', False)), 'ddf1d839-1f46-4572-b533-75c40d40677c']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cdalden/summa_setup/model/run_summa_stats.py", line 28, in <module>
    forcing = xr.open_dataset('./forcings/'+forcing_file.strip(), engine='netcdf4')
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/api.py", line 570, in open_dataset
    backend_ds = backend.open_dataset(
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 602, in open_dataset
    store = NetCDF4DataStore.open(
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 400, in open
    return cls(manager, group=group, mode=mode, lock=lock, autoclose=autoclose)
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 347, in __init__
    self.format = self.ds.data_model
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 409, in ds
    return self._acquire()
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 403, in _acquire
    with self._manager.acquire_context(needs_lock) as root:
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/file_manager.py", line 199, in acquire_context
    file, cached = self._acquire_with_cache_info(needs_lock)
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/file_manager.py", line 217, in _acquire_with_cache_info
    file = self._opener(*self._args, **kwargs)
  File "src/netCDF4/_netCDF4.pyx", line 2330, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 1948, in netCDF4._netCDF4._ensure_nc_success
FileNotFoundError: [Errno 2] No such file or directory: b'/home/cdalden/summa_setup/model/forcings/grandtarghee_current_WY00.nc'
summa run for grandtarghee_current_WY00 complete, check output folder for output file
No ACCUMULATED PRECIPITATION found for MyStation
No AIR TEMP found for MyStation
Traceback (most recent call last):
  File "/home/cdalden/summa_setup/model/snotel_to_pysumma_current.py", line 111, in <module>
    df.reset_index(inplace=True)
AttributeError: 'NoneType' object has no attribute 'reset_index'
forcing file created, now running summa
Traceback (most recent call last):
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/file_manager.py", line 211, in _acquire_with_cache_info
    file = self._cache[self._key]
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/lru_cache.py", line 56, in __getitem__
    value = self._cache[key]
KeyError: [<class 'netCDF4._netCDF4.Dataset'>, ('/home/cdalden/summa_setup/model/forcings/grandtarghee_current_WY01.nc',), 'r', (('clobber', True), ('diskless', False), ('format', 'NETCDF4'), ('persist', False)), '47124650-7d5c-47be-aa8e-270edd7d29bd']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cdalden/summa_setup/model/run_summa_stats.py", line 28, in <module>
    forcing = xr.open_dataset('./forcings/'+forcing_file.strip(), engine='netcdf4')
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/api.py", line 570, in open_dataset
    backend_ds = backend.open_dataset(
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 602, in open_dataset
    store = NetCDF4DataStore.open(
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 400, in open
    return cls(manager, group=group, mode=mode, lock=lock, autoclose=autoclose)
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 347, in __init__
    self.format = self.ds.data_model
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 409, in ds
    return self._acquire()
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 403, in _acquire
    with self._manager.acquire_context(needs_lock) as root:
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/file_manager.py", line 199, in acquire_context
    file, cached = self._acquire_with_cache_info(needs_lock)
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/file_manager.py", line 217, in _acquire_with_cache_info
    file = self._opener(*self._args, **kwargs)
  File "src/netCDF4/_netCDF4.pyx", line 2330, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 1948, in netCDF4._netCDF4._ensure_nc_success
FileNotFoundError: [Errno 2] No such file or directory: b'/home/cdalden/summa_setup/model/forcings/grandtarghee_current_WY01.nc'
summa run for grandtarghee_current_WY01 complete, check output folder for output file
No ACCUMULATED PRECIPITATION found for MyStation
No AIR TEMP found for MyStation
Traceback (most recent call last):
  File "/home/cdalden/summa_setup/model/snotel_to_pysumma_current.py", line 111, in <module>
    df.reset_index(inplace=True)
AttributeError: 'NoneType' object has no attribute 'reset_index'
forcing file created, now running summa
Traceback (most recent call last):
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/file_manager.py", line 211, in _acquire_with_cache_info
    file = self._cache[self._key]
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/lru_cache.py", line 56, in __getitem__
    value = self._cache[key]
KeyError: [<class 'netCDF4._netCDF4.Dataset'>, ('/home/cdalden/summa_setup/model/forcings/grandtarghee_current_WY02.nc',), 'r', (('clobber', True), ('diskless', False), ('format', 'NETCDF4'), ('persist', False)), 'f131b569-77b7-44b2-b07c-49c413cd5784']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cdalden/summa_setup/model/run_summa_stats.py", line 28, in <module>
    forcing = xr.open_dataset('./forcings/'+forcing_file.strip(), engine='netcdf4')
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/api.py", line 570, in open_dataset
    backend_ds = backend.open_dataset(
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 602, in open_dataset
    store = NetCDF4DataStore.open(
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 400, in open
    return cls(manager, group=group, mode=mode, lock=lock, autoclose=autoclose)
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 347, in __init__
    self.format = self.ds.data_model
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 409, in ds
    return self._acquire()
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 403, in _acquire
    with self._manager.acquire_context(needs_lock) as root:
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/file_manager.py", line 199, in acquire_context
    file, cached = self._acquire_with_cache_info(needs_lock)
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/file_manager.py", line 217, in _acquire_with_cache_info
    file = self._opener(*self._args, **kwargs)
  File "src/netCDF4/_netCDF4.pyx", line 2330, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 1948, in netCDF4._netCDF4._ensure_nc_success
FileNotFoundError: [Errno 2] No such file or directory: b'/home/cdalden/summa_setup/model/forcings/grandtarghee_current_WY02.nc'
summa run for grandtarghee_current_WY02 complete, check output folder for output file
No ACCUMULATED PRECIPITATION found for MyStation
No AIR TEMP found for MyStation
Traceback (most recent call last):
  File "/home/cdalden/summa_setup/model/snotel_to_pysumma_current.py", line 111, in <module>
    df.reset_index(inplace=True)
AttributeError: 'NoneType' object has no attribute 'reset_index'
forcing file created, now running summa
Traceback (most recent call last):
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/file_manager.py", line 211, in _acquire_with_cache_info
    file = self._cache[self._key]
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/lru_cache.py", line 56, in __getitem__
    value = self._cache[key]
KeyError: [<class 'netCDF4._netCDF4.Dataset'>, ('/home/cdalden/summa_setup/model/forcings/grandtarghee_current_WY03.nc',), 'r', (('clobber', True), ('diskless', False), ('format', 'NETCDF4'), ('persist', False)), '5476cedb-cd6f-4b71-a9b9-187a8f9ab435']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cdalden/summa_setup/model/run_summa_stats.py", line 28, in <module>
    forcing = xr.open_dataset('./forcings/'+forcing_file.strip(), engine='netcdf4')
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/api.py", line 570, in open_dataset
    backend_ds = backend.open_dataset(
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 602, in open_dataset
    store = NetCDF4DataStore.open(
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 400, in open
    return cls(manager, group=group, mode=mode, lock=lock, autoclose=autoclose)
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 347, in __init__
    self.format = self.ds.data_model
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 409, in ds
    return self._acquire()
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 403, in _acquire
    with self._manager.acquire_context(needs_lock) as root:
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/file_manager.py", line 199, in acquire_context
    file, cached = self._acquire_with_cache_info(needs_lock)
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/file_manager.py", line 217, in _acquire_with_cache_info
    file = self._opener(*self._args, **kwargs)
  File "src/netCDF4/_netCDF4.pyx", line 2330, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 1948, in netCDF4._netCDF4._ensure_nc_success
FileNotFoundError: [Errno 2] No such file or directory: b'/home/cdalden/summa_setup/model/forcings/grandtarghee_current_WY03.nc'
summa run for grandtarghee_current_WY03 complete, check output folder for output file
No ACCUMULATED PRECIPITATION found for MyStation
No AIR TEMP found for MyStation
Traceback (most recent call last):
  File "/home/cdalden/summa_setup/model/snotel_to_pysumma_current.py", line 111, in <module>
    df.reset_index(inplace=True)
AttributeError: 'NoneType' object has no attribute 'reset_index'
forcing file created, now running summa
Traceback (most recent call last):
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/file_manager.py", line 211, in _acquire_with_cache_info
    file = self._cache[self._key]
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/lru_cache.py", line 56, in __getitem__
    value = self._cache[key]
KeyError: [<class 'netCDF4._netCDF4.Dataset'>, ('/home/cdalden/summa_setup/model/forcings/grandtarghee_current_WY04.nc',), 'r', (('clobber', True), ('diskless', False), ('format', 'NETCDF4'), ('persist', False)), '7160176f-4db3-492c-8ca4-4cc33b8b15a4']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cdalden/summa_setup/model/run_summa_stats.py", line 28, in <module>
    forcing = xr.open_dataset('./forcings/'+forcing_file.strip(), engine='netcdf4')
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/api.py", line 570, in open_dataset
    backend_ds = backend.open_dataset(
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 602, in open_dataset
    store = NetCDF4DataStore.open(
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 400, in open
    return cls(manager, group=group, mode=mode, lock=lock, autoclose=autoclose)
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 347, in __init__
    self.format = self.ds.data_model
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 409, in ds
    return self._acquire()
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 403, in _acquire
    with self._manager.acquire_context(needs_lock) as root:
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/file_manager.py", line 199, in acquire_context
    file, cached = self._acquire_with_cache_info(needs_lock)
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/file_manager.py", line 217, in _acquire_with_cache_info
    file = self._opener(*self._args, **kwargs)
  File "src/netCDF4/_netCDF4.pyx", line 2330, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 1948, in netCDF4._netCDF4._ensure_nc_success
FileNotFoundError: [Errno 2] No such file or directory: b'/home/cdalden/summa_setup/model/forcings/grandtarghee_current_WY04.nc'
summa run for grandtarghee_current_WY04 complete, check output folder for output file
No ACCUMULATED PRECIPITATION found for MyStation
No AIR TEMP found for MyStation
Traceback (most recent call last):
  File "/home/cdalden/summa_setup/model/snotel_to_pysumma_current.py", line 111, in <module>
    df.reset_index(inplace=True)
AttributeError: 'NoneType' object has no attribute 'reset_index'
forcing file created, now running summa
Traceback (most recent call last):
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/file_manager.py", line 211, in _acquire_with_cache_info
    file = self._cache[self._key]
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/lru_cache.py", line 56, in __getitem__
    value = self._cache[key]
KeyError: [<class 'netCDF4._netCDF4.Dataset'>, ('/home/cdalden/summa_setup/model/forcings/grandtarghee_current_WY05.nc',), 'r', (('clobber', True), ('diskless', False), ('format', 'NETCDF4'), ('persist', False)), 'c7460bea-6dd4-4c4f-8a70-4ec2498b03b7']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cdalden/summa_setup/model/run_summa_stats.py", line 28, in <module>
    forcing = xr.open_dataset('./forcings/'+forcing_file.strip(), engine='netcdf4')
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/api.py", line 570, in open_dataset
    backend_ds = backend.open_dataset(
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 602, in open_dataset
    store = NetCDF4DataStore.open(
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 400, in open
    return cls(manager, group=group, mode=mode, lock=lock, autoclose=autoclose)
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 347, in __init__
    self.format = self.ds.data_model
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 409, in ds
    return self._acquire()
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 403, in _acquire
    with self._manager.acquire_context(needs_lock) as root:
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/file_manager.py", line 199, in acquire_context
    file, cached = self._acquire_with_cache_info(needs_lock)
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/file_manager.py", line 217, in _acquire_with_cache_info
    file = self._opener(*self._args, **kwargs)
  File "src/netCDF4/_netCDF4.pyx", line 2330, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 1948, in netCDF4._netCDF4._ensure_nc_success
FileNotFoundError: [Errno 2] No such file or directory: b'/home/cdalden/summa_setup/model/forcings/grandtarghee_current_WY05.nc'
summa run for grandtarghee_current_WY05 complete, check output folder for output file
SNOTEL csv has no snowdepth for this run
Traceback (most recent call last):
  File "/home/cdalden/summa_setup/model/snotel_to_pysumma_current.py", line 240, in <module>
    met_data['prec'].values[:, 0, 0] = prec_vals
ValueError: could not broadcast input array from shape (37,) into shape (365,)
forcing file created, now running summa
Traceback (most recent call last):
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/file_manager.py", line 211, in _acquire_with_cache_info
    file = self._cache[self._key]
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/lru_cache.py", line 56, in __getitem__
    value = self._cache[key]
KeyError: [<class 'netCDF4._netCDF4.Dataset'>, ('/home/cdalden/summa_setup/model/forcings/grandtarghee_current_WY06.nc',), 'r', (('clobber', True), ('diskless', False), ('format', 'NETCDF4'), ('persist', False)), '28ac5bbf-070e-4d33-b553-c834c591b35f']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cdalden/summa_setup/model/run_summa_stats.py", line 28, in <module>
    forcing = xr.open_dataset('./forcings/'+forcing_file.strip(), engine='netcdf4')
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/api.py", line 570, in open_dataset
    backend_ds = backend.open_dataset(
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 602, in open_dataset
    store = NetCDF4DataStore.open(
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 400, in open
    return cls(manager, group=group, mode=mode, lock=lock, autoclose=autoclose)
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 347, in __init__
    self.format = self.ds.data_model
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 409, in ds
    return self._acquire()
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 403, in _acquire
    with self._manager.acquire_context(needs_lock) as root:
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/file_manager.py", line 199, in acquire_context
    file, cached = self._acquire_with_cache_info(needs_lock)
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/file_manager.py", line 217, in _acquire_with_cache_info
    file = self._opener(*self._args, **kwargs)
  File "src/netCDF4/_netCDF4.pyx", line 2330, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 1948, in netCDF4._netCDF4._ensure_nc_success
FileNotFoundError: [Errno 2] No such file or directory: b'/home/cdalden/summa_setup/model/forcings/grandtarghee_current_WY06.nc'
summa run for grandtarghee_current_WY06 complete, check output folder for output file
SNOTEL csv has no snowdepth for this run
Traceback (most recent call last):
  File "/home/cdalden/summa_setup/model/snotel_to_pysumma_current.py", line 286, in <module>
    state['prec'].values[:, 0, 0] = prec_vals
ValueError: could not broadcast input array from shape (37,) into shape (90,)
forcing file created, now running summa
Traceback (most recent call last):
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/file_manager.py", line 211, in _acquire_with_cache_info
    file = self._cache[self._key]
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/lru_cache.py", line 56, in __getitem__
    value = self._cache[key]
KeyError: [<class 'netCDF4._netCDF4.Dataset'>, ('/home/cdalden/summa_setup/model/forcings/grandtarghee_current_WY07.nc',), 'r', (('clobber', True), ('diskless', False), ('format', 'NETCDF4'), ('persist', False)), 'dc6bcee0-6062-4dcb-96a6-345532082808']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cdalden/summa_setup/model/run_summa_stats.py", line 28, in <module>
    forcing = xr.open_dataset('./forcings/'+forcing_file.strip(), engine='netcdf4')
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/api.py", line 570, in open_dataset
    backend_ds = backend.open_dataset(
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 602, in open_dataset
    store = NetCDF4DataStore.open(
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 400, in open
    return cls(manager, group=group, mode=mode, lock=lock, autoclose=autoclose)
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 347, in __init__
    self.format = self.ds.data_model
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 409, in ds
    return self._acquire()
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 403, in _acquire
    with self._manager.acquire_context(needs_lock) as root:
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/file_manager.py", line 199, in acquire_context
    file, cached = self._acquire_with_cache_info(needs_lock)
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/file_manager.py", line 217, in _acquire_with_cache_info
    file = self._opener(*self._args, **kwargs)
  File "src/netCDF4/_netCDF4.pyx", line 2330, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 1948, in netCDF4._netCDF4._ensure_nc_success
FileNotFoundError: [Errno 2] No such file or directory: b'/home/cdalden/summa_setup/model/forcings/grandtarghee_current_WY07.nc'
summa run for grandtarghee_current_WY07 complete, check output folder for output file
SNOTEL csv has no snowdepth for this run
forcing file created, now running summa
Model status: Success
number of crust days:52.541666666666664
summa run for grandtarghee_current_WY08 complete, check output folder for output file
SNOTEL csv has no snowdepth for this run
forcing file created, now running summa
Model status: Success
number of crust days:51.333333333333336
summa run for grandtarghee_current_WY09 complete, check output folder for output file
SNOTEL csv has no snowdepth for this run
forcing file created, now running summa
Model status: Success
number of crust days:72.95833333333333
summa run for grandtarghee_current_WY10 complete, check output folder for output file
SNOTEL csv has no snowdepth for this run
forcing file created, now running summa
Model status: Success
number of crust days:56.875
summa run for grandtarghee_current_WY11 complete, check output folder for output file
SNOTEL csv has no snowdepth for this run
forcing file created, now running summa
Model status: Success
number of crust days:59.375
summa run for grandtarghee_current_WY12 complete, check output folder for output file
SNOTEL csv has no snowdepth for this run
forcing file created, now running summa
Model status: Success
number of crust days:23.583333333333332
summa run for grandtarghee_current_WY13 complete, check output folder for output file
SNOTEL csv has no snowdepth for this run
forcing file created, now running summa
Model status: Success
number of crust days:30.625
summa run for grandtarghee_current_WY14 complete, check output folder for output file
SNOTEL csv has no snowdepth for this run
forcing file created, now running summa
Model status: Success
number of crust days:33.666666666666664
summa run for grandtarghee_current_WY15 complete, check output folder for output file
SNOTEL csv has no snowdepth for this run
forcing file created, now running summa
Model status: Success
number of crust days:30.666666666666668
summa run for grandtarghee_current_WY16 complete, check output folder for output file
SNOTEL csv has no snowdepth for this run
forcing file created, now running summa
Model status: Success
number of crust days:56.958333333333336
summa run for grandtarghee_current_WY17 complete, check output folder for output file
SNOTEL csv has no snowdepth for this run
forcing file created, now running summa
Model status: Success
number of crust days:23.291666666666668
summa run for grandtarghee_current_WY18 complete, check output folder for output file
SNOTEL csv has no snowdepth for this run
forcing file created, now running summa
Model status: Success
number of crust days:44.708333333333336
summa run for grandtarghee_current_WY19 complete, check output folder for output file
SNOTEL csv has no snowdepth for this run
forcing file created, now running summa
Model status: Success
number of crust days:31.125
summa run for grandtarghee_current_WY20 complete, check output folder for output file
SNOTEL csv has no snowdepth for this run
forcing file created, now running summa
Model status: Success
number of crust days:155.70833333333334
summa run for grandtarghee_current_WY21 complete, check output folder for output file
SNOTEL csv has no snowdepth for this run
forcing file created, now running summa
Model status: Success
number of crust days:64.75
summa run for grandtarghee_current_WY22 complete, check output folder for output file
SNOTEL csv has no snowdepth for this run
forcing file created, now running summa
Model status: Success
number of crust days:28.625
summa run for grandtarghee_current_WY23 complete, check output folder for output file
SNOTEL csv has no snowdepth for this run
forcing file created, now running summa
Model status: Success
number of crust days:61.958333333333336
summa run for grandtarghee_current_WY24 complete, check output folder for output file
Enter the desired SNOTEL site code (ie. 1107:WA): Enter the water year: Enter the output file name (ie. buck_WY16): No ACCUMULATED PRECIPITATION found for MyStation
No AIR TEMP found for MyStation
No SWE found for MyStation
No SNOWDEPTH found for MyStation
********** generating the forcing file, please be patient **********
********** should take ~3 minutes to run **********
Traceback (most recent call last):
  File "/home/cdalden/summa_setup/model/snotel_to_pysumma_+2K.py", line 112, in <module>
    df.reset_index(inplace=True)
AttributeError: 'NoneType' object has no attribute 'reset_index'
forcing file created, now running summa
Traceback (most recent call last):
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/file_manager.py", line 211, in _acquire_with_cache_info
    file = self._cache[self._key]
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/lru_cache.py", line 56, in __getitem__
    value = self._cache[key]
KeyError: [<class 'netCDF4._netCDF4.Dataset'>, ('/home/cdalden/summa_setup/model/forcings/grandtarghee_+2K_WY00.nc',), 'r', (('clobber', True), ('diskless', False), ('format', 'NETCDF4'), ('persist', False)), '774b1ffd-14da-4a7e-be1c-d956b39d57d3']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cdalden/summa_setup/model/run_summa_stats.py", line 28, in <module>
    forcing = xr.open_dataset('./forcings/'+forcing_file.strip(), engine='netcdf4')
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/api.py", line 570, in open_dataset
    backend_ds = backend.open_dataset(
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 602, in open_dataset
    store = NetCDF4DataStore.open(
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 400, in open
    return cls(manager, group=group, mode=mode, lock=lock, autoclose=autoclose)
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 347, in __init__
    self.format = self.ds.data_model
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 409, in ds
    return self._acquire()
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 403, in _acquire
    with self._manager.acquire_context(needs_lock) as root:
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/file_manager.py", line 199, in acquire_context
    file, cached = self._acquire_with_cache_info(needs_lock)
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/file_manager.py", line 217, in _acquire_with_cache_info
    file = self._opener(*self._args, **kwargs)
  File "src/netCDF4/_netCDF4.pyx", line 2330, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 1948, in netCDF4._netCDF4._ensure_nc_success
FileNotFoundError: [Errno 2] No such file or directory: b'/home/cdalden/summa_setup/model/forcings/grandtarghee_+2K_WY00.nc'
summa run for grandtarghee_+2K_WY00 complete, check output folder for output file
Enter the desired SNOTEL site code (ie. 1107:WA): Enter the water year: Enter the output file name (ie. buck_WY16): No ACCUMULATED PRECIPITATION found for MyStation
No AIR TEMP found for MyStation
No SWE found for MyStation
No SNOWDEPTH found for MyStation
********** generating the forcing file, please be patient **********
********** should take ~3 minutes to run **********
Traceback (most recent call last):
  File "/home/cdalden/summa_setup/model/snotel_to_pysumma_+2K.py", line 112, in <module>
    df.reset_index(inplace=True)
AttributeError: 'NoneType' object has no attribute 'reset_index'
forcing file created, now running summa
Traceback (most recent call last):
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/file_manager.py", line 211, in _acquire_with_cache_info
    file = self._cache[self._key]
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/lru_cache.py", line 56, in __getitem__
    value = self._cache[key]
KeyError: [<class 'netCDF4._netCDF4.Dataset'>, ('/home/cdalden/summa_setup/model/forcings/grandtarghee_+2K_WY01.nc',), 'r', (('clobber', True), ('diskless', False), ('format', 'NETCDF4'), ('persist', False)), 'f3eccd40-a217-4ab9-aa72-d394b7996584']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cdalden/summa_setup/model/run_summa_stats.py", line 28, in <module>
    forcing = xr.open_dataset('./forcings/'+forcing_file.strip(), engine='netcdf4')
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/api.py", line 570, in open_dataset
    backend_ds = backend.open_dataset(
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 602, in open_dataset
    store = NetCDF4DataStore.open(
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 400, in open
    return cls(manager, group=group, mode=mode, lock=lock, autoclose=autoclose)
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 347, in __init__
    self.format = self.ds.data_model
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 409, in ds
    return self._acquire()
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 403, in _acquire
    with self._manager.acquire_context(needs_lock) as root:
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/file_manager.py", line 199, in acquire_context
    file, cached = self._acquire_with_cache_info(needs_lock)
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/file_manager.py", line 217, in _acquire_with_cache_info
    file = self._opener(*self._args, **kwargs)
  File "src/netCDF4/_netCDF4.pyx", line 2330, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 1948, in netCDF4._netCDF4._ensure_nc_success
FileNotFoundError: [Errno 2] No such file or directory: b'/home/cdalden/summa_setup/model/forcings/grandtarghee_+2K_WY01.nc'
summa run for grandtarghee_+2K_WY01 complete, check output folder for output file
Enter the desired SNOTEL site code (ie. 1107:WA): Enter the water year: Enter the output file name (ie. buck_WY16): No ACCUMULATED PRECIPITATION found for MyStation
No AIR TEMP found for MyStation
No SWE found for MyStation
No SNOWDEPTH found for MyStation
********** generating the forcing file, please be patient **********
********** should take ~3 minutes to run **********
Traceback (most recent call last):
  File "/home/cdalden/summa_setup/model/snotel_to_pysumma_+2K.py", line 112, in <module>
    df.reset_index(inplace=True)
AttributeError: 'NoneType' object has no attribute 'reset_index'
forcing file created, now running summa
Traceback (most recent call last):
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/file_manager.py", line 211, in _acquire_with_cache_info
    file = self._cache[self._key]
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/lru_cache.py", line 56, in __getitem__
    value = self._cache[key]
KeyError: [<class 'netCDF4._netCDF4.Dataset'>, ('/home/cdalden/summa_setup/model/forcings/grandtarghee_+2K_WY02.nc',), 'r', (('clobber', True), ('diskless', False), ('format', 'NETCDF4'), ('persist', False)), 'a45a990d-9e69-4e94-8a98-d9795c369aab']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cdalden/summa_setup/model/run_summa_stats.py", line 28, in <module>
    forcing = xr.open_dataset('./forcings/'+forcing_file.strip(), engine='netcdf4')
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/api.py", line 570, in open_dataset
    backend_ds = backend.open_dataset(
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 602, in open_dataset
    store = NetCDF4DataStore.open(
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 400, in open
    return cls(manager, group=group, mode=mode, lock=lock, autoclose=autoclose)
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 347, in __init__
    self.format = self.ds.data_model
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 409, in ds
    return self._acquire()
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 403, in _acquire
    with self._manager.acquire_context(needs_lock) as root:
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/file_manager.py", line 199, in acquire_context
    file, cached = self._acquire_with_cache_info(needs_lock)
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/file_manager.py", line 217, in _acquire_with_cache_info
    file = self._opener(*self._args, **kwargs)
  File "src/netCDF4/_netCDF4.pyx", line 2330, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 1948, in netCDF4._netCDF4._ensure_nc_success
FileNotFoundError: [Errno 2] No such file or directory: b'/home/cdalden/summa_setup/model/forcings/grandtarghee_+2K_WY02.nc'
summa run for grandtarghee_+2K_WY02 complete, check output folder for output file
Enter the desired SNOTEL site code (ie. 1107:WA): Enter the water year: Enter the output file name (ie. buck_WY16): No ACCUMULATED PRECIPITATION found for MyStation
No AIR TEMP found for MyStation
No SWE found for MyStation
No SNOWDEPTH found for MyStation
********** generating the forcing file, please be patient **********
********** should take ~3 minutes to run **********
Traceback (most recent call last):
  File "/home/cdalden/summa_setup/model/snotel_to_pysumma_+2K.py", line 112, in <module>
    df.reset_index(inplace=True)
AttributeError: 'NoneType' object has no attribute 'reset_index'
forcing file created, now running summa
Traceback (most recent call last):
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/file_manager.py", line 211, in _acquire_with_cache_info
    file = self._cache[self._key]
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/lru_cache.py", line 56, in __getitem__
    value = self._cache[key]
KeyError: [<class 'netCDF4._netCDF4.Dataset'>, ('/home/cdalden/summa_setup/model/forcings/grandtarghee_+2K_WY03.nc',), 'r', (('clobber', True), ('diskless', False), ('format', 'NETCDF4'), ('persist', False)), 'b69b412d-7cb4-4b0d-b293-f8c2b936a0ea']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cdalden/summa_setup/model/run_summa_stats.py", line 28, in <module>
    forcing = xr.open_dataset('./forcings/'+forcing_file.strip(), engine='netcdf4')
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/api.py", line 570, in open_dataset
    backend_ds = backend.open_dataset(
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 602, in open_dataset
    store = NetCDF4DataStore.open(
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 400, in open
    return cls(manager, group=group, mode=mode, lock=lock, autoclose=autoclose)
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 347, in __init__
    self.format = self.ds.data_model
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 409, in ds
    return self._acquire()
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 403, in _acquire
    with self._manager.acquire_context(needs_lock) as root:
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/file_manager.py", line 199, in acquire_context
    file, cached = self._acquire_with_cache_info(needs_lock)
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/file_manager.py", line 217, in _acquire_with_cache_info
    file = self._opener(*self._args, **kwargs)
  File "src/netCDF4/_netCDF4.pyx", line 2330, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 1948, in netCDF4._netCDF4._ensure_nc_success
FileNotFoundError: [Errno 2] No such file or directory: b'/home/cdalden/summa_setup/model/forcings/grandtarghee_+2K_WY03.nc'
summa run for grandtarghee_+2K_WY03 complete, check output folder for output file
Enter the desired SNOTEL site code (ie. 1107:WA): Enter the water year: Enter the output file name (ie. buck_WY16): No ACCUMULATED PRECIPITATION found for MyStation
No AIR TEMP found for MyStation
No SWE found for MyStation
No SNOWDEPTH found for MyStation
********** generating the forcing file, please be patient **********
********** should take ~3 minutes to run **********
Traceback (most recent call last):
  File "/home/cdalden/summa_setup/model/snotel_to_pysumma_+2K.py", line 112, in <module>
    df.reset_index(inplace=True)
AttributeError: 'NoneType' object has no attribute 'reset_index'
forcing file created, now running summa
Traceback (most recent call last):
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/file_manager.py", line 211, in _acquire_with_cache_info
    file = self._cache[self._key]
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/lru_cache.py", line 56, in __getitem__
    value = self._cache[key]
KeyError: [<class 'netCDF4._netCDF4.Dataset'>, ('/home/cdalden/summa_setup/model/forcings/grandtarghee_+2K_WY04.nc',), 'r', (('clobber', True), ('diskless', False), ('format', 'NETCDF4'), ('persist', False)), '129e7170-0fcf-4fa2-9c9e-49c0bf5c6870']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cdalden/summa_setup/model/run_summa_stats.py", line 28, in <module>
    forcing = xr.open_dataset('./forcings/'+forcing_file.strip(), engine='netcdf4')
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/api.py", line 570, in open_dataset
    backend_ds = backend.open_dataset(
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 602, in open_dataset
    store = NetCDF4DataStore.open(
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 400, in open
    return cls(manager, group=group, mode=mode, lock=lock, autoclose=autoclose)
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 347, in __init__
    self.format = self.ds.data_model
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 409, in ds
    return self._acquire()
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 403, in _acquire
    with self._manager.acquire_context(needs_lock) as root:
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/file_manager.py", line 199, in acquire_context
    file, cached = self._acquire_with_cache_info(needs_lock)
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/file_manager.py", line 217, in _acquire_with_cache_info
    file = self._opener(*self._args, **kwargs)
  File "src/netCDF4/_netCDF4.pyx", line 2330, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 1948, in netCDF4._netCDF4._ensure_nc_success
FileNotFoundError: [Errno 2] No such file or directory: b'/home/cdalden/summa_setup/model/forcings/grandtarghee_+2K_WY04.nc'
summa run for grandtarghee_+2K_WY04 complete, check output folder for output file
Enter the desired SNOTEL site code (ie. 1107:WA): Enter the water year: Enter the output file name (ie. buck_WY16): No ACCUMULATED PRECIPITATION found for MyStation
No AIR TEMP found for MyStation
No SWE found for MyStation
No SNOWDEPTH found for MyStation
********** generating the forcing file, please be patient **********
********** should take ~3 minutes to run **********
Traceback (most recent call last):
  File "/home/cdalden/summa_setup/model/snotel_to_pysumma_+2K.py", line 112, in <module>
    df.reset_index(inplace=True)
AttributeError: 'NoneType' object has no attribute 'reset_index'
forcing file created, now running summa
Traceback (most recent call last):
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/file_manager.py", line 211, in _acquire_with_cache_info
    file = self._cache[self._key]
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/lru_cache.py", line 56, in __getitem__
    value = self._cache[key]
KeyError: [<class 'netCDF4._netCDF4.Dataset'>, ('/home/cdalden/summa_setup/model/forcings/grandtarghee_+2K_WY05.nc',), 'r', (('clobber', True), ('diskless', False), ('format', 'NETCDF4'), ('persist', False)), 'e0dee5f6-7533-40b2-ad82-8f2ef17c2b2d']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cdalden/summa_setup/model/run_summa_stats.py", line 28, in <module>
    forcing = xr.open_dataset('./forcings/'+forcing_file.strip(), engine='netcdf4')
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/api.py", line 570, in open_dataset
    backend_ds = backend.open_dataset(
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 602, in open_dataset
    store = NetCDF4DataStore.open(
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 400, in open
    return cls(manager, group=group, mode=mode, lock=lock, autoclose=autoclose)
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 347, in __init__
    self.format = self.ds.data_model
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 409, in ds
    return self._acquire()
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 403, in _acquire
    with self._manager.acquire_context(needs_lock) as root:
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/file_manager.py", line 199, in acquire_context
    file, cached = self._acquire_with_cache_info(needs_lock)
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/file_manager.py", line 217, in _acquire_with_cache_info
    file = self._opener(*self._args, **kwargs)
  File "src/netCDF4/_netCDF4.pyx", line 2330, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 1948, in netCDF4._netCDF4._ensure_nc_success
FileNotFoundError: [Errno 2] No such file or directory: b'/home/cdalden/summa_setup/model/forcings/grandtarghee_+2K_WY05.nc'
summa run for grandtarghee_+2K_WY05 complete, check output folder for output file
Enter the desired SNOTEL site code (ie. 1107:WA): Enter the water year: Enter the output file name (ie. buck_WY16): ********** generating the forcing file, please be patient **********
********** should take ~3 minutes to run **********
Traceback (most recent call last):
  File "/home/cdalden/summa_setup/model/snotel_to_pysumma_+2K.py", line 241, in <module>
    met_data['prec'].values[:, 0, 0] = prec_vals
ValueError: could not broadcast input array from shape (37,) into shape (365,)
forcing file created, now running summa
Traceback (most recent call last):
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/file_manager.py", line 211, in _acquire_with_cache_info
    file = self._cache[self._key]
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/lru_cache.py", line 56, in __getitem__
    value = self._cache[key]
KeyError: [<class 'netCDF4._netCDF4.Dataset'>, ('/home/cdalden/summa_setup/model/forcings/grandtarghee_+2K_WY06.nc',), 'r', (('clobber', True), ('diskless', False), ('format', 'NETCDF4'), ('persist', False)), '0d8b8f65-f7ac-4b2e-b0a4-d130e1ca407a']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cdalden/summa_setup/model/run_summa_stats.py", line 28, in <module>
    forcing = xr.open_dataset('./forcings/'+forcing_file.strip(), engine='netcdf4')
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/api.py", line 570, in open_dataset
    backend_ds = backend.open_dataset(
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 602, in open_dataset
    store = NetCDF4DataStore.open(
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 400, in open
    return cls(manager, group=group, mode=mode, lock=lock, autoclose=autoclose)
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 347, in __init__
    self.format = self.ds.data_model
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 409, in ds
    return self._acquire()
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 403, in _acquire
    with self._manager.acquire_context(needs_lock) as root:
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/file_manager.py", line 199, in acquire_context
    file, cached = self._acquire_with_cache_info(needs_lock)
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/file_manager.py", line 217, in _acquire_with_cache_info
    file = self._opener(*self._args, **kwargs)
  File "src/netCDF4/_netCDF4.pyx", line 2330, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 1948, in netCDF4._netCDF4._ensure_nc_success
FileNotFoundError: [Errno 2] No such file or directory: b'/home/cdalden/summa_setup/model/forcings/grandtarghee_+2K_WY06.nc'
summa run for grandtarghee_+2K_WY06 complete, check output folder for output file
Enter the desired SNOTEL site code (ie. 1107:WA): Enter the water year: Enter the output file name (ie. buck_WY16): ********** generating the forcing file, please be patient **********
********** should take ~3 minutes to run **********
Traceback (most recent call last):
  File "/home/cdalden/summa_setup/model/snotel_to_pysumma_+2K.py", line 287, in <module>
    state['prec'].values[:, 0, 0] = prec_vals
ValueError: could not broadcast input array from shape (37,) into shape (90,)
forcing file created, now running summa
Traceback (most recent call last):
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/file_manager.py", line 211, in _acquire_with_cache_info
    file = self._cache[self._key]
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/lru_cache.py", line 56, in __getitem__
    value = self._cache[key]
KeyError: [<class 'netCDF4._netCDF4.Dataset'>, ('/home/cdalden/summa_setup/model/forcings/grandtarghee_+2K_WY07.nc',), 'r', (('clobber', True), ('diskless', False), ('format', 'NETCDF4'), ('persist', False)), '7b82c0a5-1f26-4c7d-a24c-f269689ba3bb']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cdalden/summa_setup/model/run_summa_stats.py", line 28, in <module>
    forcing = xr.open_dataset('./forcings/'+forcing_file.strip(), engine='netcdf4')
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/api.py", line 570, in open_dataset
    backend_ds = backend.open_dataset(
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 602, in open_dataset
    store = NetCDF4DataStore.open(
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 400, in open
    return cls(manager, group=group, mode=mode, lock=lock, autoclose=autoclose)
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 347, in __init__
    self.format = self.ds.data_model
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 409, in ds
    return self._acquire()
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 403, in _acquire
    with self._manager.acquire_context(needs_lock) as root:
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/file_manager.py", line 199, in acquire_context
    file, cached = self._acquire_with_cache_info(needs_lock)
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/file_manager.py", line 217, in _acquire_with_cache_info
    file = self._opener(*self._args, **kwargs)
  File "src/netCDF4/_netCDF4.pyx", line 2330, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 1948, in netCDF4._netCDF4._ensure_nc_success
FileNotFoundError: [Errno 2] No such file or directory: b'/home/cdalden/summa_setup/model/forcings/grandtarghee_+2K_WY07.nc'
summa run for grandtarghee_+2K_WY07 complete, check output folder for output file
Enter the desired SNOTEL site code (ie. 1107:WA): Enter the water year: Enter the output file name (ie. buck_WY16): ********** generating the forcing file, please be patient **********
********** should take ~3 minutes to run **********
forcing file created, now running summa
Model status: Success
number of crust days:72.70833333333333
summa run for grandtarghee_+2K_WY08 complete, check output folder for output file
Enter the desired SNOTEL site code (ie. 1107:WA): Enter the water year: Enter the output file name (ie. buck_WY16): ********** generating the forcing file, please be patient **********
********** should take ~3 minutes to run **********
forcing file created, now running summa
Model status: Success
number of crust days:52.625
summa run for grandtarghee_+2K_WY09 complete, check output folder for output file
Enter the desired SNOTEL site code (ie. 1107:WA): Enter the water year: Enter the output file name (ie. buck_WY16): ********** generating the forcing file, please be patient **********
********** should take ~3 minutes to run **********
forcing file created, now running summa
Model status: Success
number of crust days:110.0
summa run for grandtarghee_+2K_WY10 complete, check output folder for output file
Enter the desired SNOTEL site code (ie. 1107:WA): Enter the water year: Enter the output file name (ie. buck_WY16): ********** generating the forcing file, please be patient **********
********** should take ~3 minutes to run **********
forcing file created, now running summa
Model status: Success
number of crust days:41.166666666666664
summa run for grandtarghee_+2K_WY11 complete, check output folder for output file
Enter the desired SNOTEL site code (ie. 1107:WA): Enter the water year: Enter the output file name (ie. buck_WY16): ********** generating the forcing file, please be patient **********
********** should take ~3 minutes to run **********
forcing file created, now running summa
Model status: Success
number of crust days:76.29166666666667
summa run for grandtarghee_+2K_WY12 complete, check output folder for output file
Enter the desired SNOTEL site code (ie. 1107:WA): Enter the water year: Enter the output file name (ie. buck_WY16): ********** generating the forcing file, please be patient **********
********** should take ~3 minutes to run **********
forcing file created, now running summa
Model status: Success
number of crust days:22.916666666666668
summa run for grandtarghee_+2K_WY13 complete, check output folder for output file
Enter the desired SNOTEL site code (ie. 1107:WA): Enter the water year: Enter the output file name (ie. buck_WY16): ********** generating the forcing file, please be patient **********
********** should take ~3 minutes to run **********
forcing file created, now running summa
Model status: Success
number of crust days:36.5
summa run for grandtarghee_+2K_WY14 complete, check output folder for output file
Enter the desired SNOTEL site code (ie. 1107:WA): Enter the water year: Enter the output file name (ie. buck_WY16): ********** generating the forcing file, please be patient **********
********** should take ~3 minutes to run **********
forcing file created, now running summa
Model status: Success
number of crust days:77.20833333333333
summa run for grandtarghee_+2K_WY15 complete, check output folder for output file
Enter the desired SNOTEL site code (ie. 1107:WA): Enter the water year: Enter the output file name (ie. buck_WY16): ********** generating the forcing file, please be patient **********
********** should take ~3 minutes to run **********
forcing file created, now running summa
Model status: Success
number of crust days:40.166666666666664
summa run for grandtarghee_+2K_WY16 complete, check output folder for output file
Enter the desired SNOTEL site code (ie. 1107:WA): Enter the water year: Enter the output file name (ie. buck_WY16): ********** generating the forcing file, please be patient **********
********** should take ~3 minutes to run **********
forcing file created, now running summa
Model status: Success
number of crust days:33.5
summa run for grandtarghee_+2K_WY17 complete, check output folder for output file
Enter the desired SNOTEL site code (ie. 1107:WA): Enter the water year: Enter the output file name (ie. buck_WY16): ********** generating the forcing file, please be patient **********
********** should take ~3 minutes to run **********
forcing file created, now running summa
Model status: Success
number of crust days:44.458333333333336
summa run for grandtarghee_+2K_WY18 complete, check output folder for output file
Enter the desired SNOTEL site code (ie. 1107:WA): Enter the water year: Enter the output file name (ie. buck_WY16): ********** generating the forcing file, please be patient **********
********** should take ~3 minutes to run **********
forcing file created, now running summa
Model status: Success
number of crust days:21.291666666666668
summa run for grandtarghee_+2K_WY19 complete, check output folder for output file
Enter the desired SNOTEL site code (ie. 1107:WA): Enter the water year: Enter the output file name (ie. buck_WY16): ********** generating the forcing file, please be patient **********
********** should take ~3 minutes to run **********
forcing file created, now running summa
Model status: Success
number of crust days:49.416666666666664
summa run for grandtarghee_+2K_WY20 complete, check output folder for output file
Enter the desired SNOTEL site code (ie. 1107:WA): Enter the water year: Enter the output file name (ie. buck_WY16): ********** generating the forcing file, please be patient **********
********** should take ~3 minutes to run **********
forcing file created, now running summa
Model status: Success
number of crust days:122.91666666666667
summa run for grandtarghee_+2K_WY21 complete, check output folder for output file
Enter the desired SNOTEL site code (ie. 1107:WA): Enter the water year: Enter the output file name (ie. buck_WY16): ********** generating the forcing file, please be patient **********
********** should take ~3 minutes to run **********
forcing file created, now running summa
Model status: Success
number of crust days:53.458333333333336
summa run for grandtarghee_+2K_WY22 complete, check output folder for output file
Enter the desired SNOTEL site code (ie. 1107:WA): Enter the water year: Enter the output file name (ie. buck_WY16): ********** generating the forcing file, please be patient **********
********** should take ~3 minutes to run **********
forcing file created, now running summa
Model status: Success
number of crust days:15.583333333333334
summa run for grandtarghee_+2K_WY23 complete, check output folder for output file
Enter the desired SNOTEL site code (ie. 1107:WA): Enter the water year: Enter the output file name (ie. buck_WY16): ********** generating the forcing file, please be patient **********
********** should take ~3 minutes to run **********
forcing file created, now running summa
Model status: Success
number of crust days:60.333333333333336
summa run for grandtarghee_+2K_WY24 complete, check output folder for output file
Enter the desired SNOTEL site code (ie. 1107:WA): Enter the water year: Enter the output file name (ie. buck_WY16): No ACCUMULATED PRECIPITATION found for MyStation
No AIR TEMP found for MyStation
No SWE found for MyStation
No SNOWDEPTH found for MyStation
********** generating the forcing file, please be patient **********
********** should take ~3 minutes to run **********
Traceback (most recent call last):
  File "/home/cdalden/summa_setup/model/snotel_to_pysumma_+4K.py", line 112, in <module>
    df.reset_index(inplace=True)
AttributeError: 'NoneType' object has no attribute 'reset_index'
forcing file created, now running summa
Traceback (most recent call last):
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/file_manager.py", line 211, in _acquire_with_cache_info
    file = self._cache[self._key]
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/lru_cache.py", line 56, in __getitem__
    value = self._cache[key]
KeyError: [<class 'netCDF4._netCDF4.Dataset'>, ('/home/cdalden/summa_setup/model/forcings/grandtarghee_+4K_WY00.nc',), 'r', (('clobber', True), ('diskless', False), ('format', 'NETCDF4'), ('persist', False)), 'b9473509-16f4-4cbb-8031-074a69c1129e']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cdalden/summa_setup/model/run_summa_stats.py", line 28, in <module>
    forcing = xr.open_dataset('./forcings/'+forcing_file.strip(), engine='netcdf4')
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/api.py", line 570, in open_dataset
    backend_ds = backend.open_dataset(
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 602, in open_dataset
    store = NetCDF4DataStore.open(
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 400, in open
    return cls(manager, group=group, mode=mode, lock=lock, autoclose=autoclose)
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 347, in __init__
    self.format = self.ds.data_model
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 409, in ds
    return self._acquire()
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 403, in _acquire
    with self._manager.acquire_context(needs_lock) as root:
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/file_manager.py", line 199, in acquire_context
    file, cached = self._acquire_with_cache_info(needs_lock)
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/file_manager.py", line 217, in _acquire_with_cache_info
    file = self._opener(*self._args, **kwargs)
  File "src/netCDF4/_netCDF4.pyx", line 2330, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 1948, in netCDF4._netCDF4._ensure_nc_success
FileNotFoundError: [Errno 2] No such file or directory: b'/home/cdalden/summa_setup/model/forcings/grandtarghee_+4K_WY00.nc'
summa run for grandtarghee_+4K_WY00 complete, check output folder for output file
Enter the desired SNOTEL site code (ie. 1107:WA): Enter the water year: Enter the output file name (ie. buck_WY16): No ACCUMULATED PRECIPITATION found for MyStation
No AIR TEMP found for MyStation
No SWE found for MyStation
No SNOWDEPTH found for MyStation
********** generating the forcing file, please be patient **********
********** should take ~3 minutes to run **********
Traceback (most recent call last):
  File "/home/cdalden/summa_setup/model/snotel_to_pysumma_+4K.py", line 112, in <module>
    df.reset_index(inplace=True)
AttributeError: 'NoneType' object has no attribute 'reset_index'
forcing file created, now running summa
Traceback (most recent call last):
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/file_manager.py", line 211, in _acquire_with_cache_info
    file = self._cache[self._key]
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/lru_cache.py", line 56, in __getitem__
    value = self._cache[key]
KeyError: [<class 'netCDF4._netCDF4.Dataset'>, ('/home/cdalden/summa_setup/model/forcings/grandtarghee_+4K_WY01.nc',), 'r', (('clobber', True), ('diskless', False), ('format', 'NETCDF4'), ('persist', False)), '3032bf37-1cfb-42b5-b79c-9d07e42028bb']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cdalden/summa_setup/model/run_summa_stats.py", line 28, in <module>
    forcing = xr.open_dataset('./forcings/'+forcing_file.strip(), engine='netcdf4')
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/api.py", line 570, in open_dataset
    backend_ds = backend.open_dataset(
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 602, in open_dataset
    store = NetCDF4DataStore.open(
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 400, in open
    return cls(manager, group=group, mode=mode, lock=lock, autoclose=autoclose)
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 347, in __init__
    self.format = self.ds.data_model
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 409, in ds
    return self._acquire()
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 403, in _acquire
    with self._manager.acquire_context(needs_lock) as root:
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/file_manager.py", line 199, in acquire_context
    file, cached = self._acquire_with_cache_info(needs_lock)
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/file_manager.py", line 217, in _acquire_with_cache_info
    file = self._opener(*self._args, **kwargs)
  File "src/netCDF4/_netCDF4.pyx", line 2330, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 1948, in netCDF4._netCDF4._ensure_nc_success
FileNotFoundError: [Errno 2] No such file or directory: b'/home/cdalden/summa_setup/model/forcings/grandtarghee_+4K_WY01.nc'
summa run for grandtarghee_+4K_WY01 complete, check output folder for output file
Enter the desired SNOTEL site code (ie. 1107:WA): Enter the water year: Enter the output file name (ie. buck_WY16): No ACCUMULATED PRECIPITATION found for MyStation
No AIR TEMP found for MyStation
No SWE found for MyStation
No SNOWDEPTH found for MyStation
********** generating the forcing file, please be patient **********
********** should take ~3 minutes to run **********
Traceback (most recent call last):
  File "/home/cdalden/summa_setup/model/snotel_to_pysumma_+4K.py", line 112, in <module>
    df.reset_index(inplace=True)
AttributeError: 'NoneType' object has no attribute 'reset_index'
forcing file created, now running summa
Traceback (most recent call last):
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/file_manager.py", line 211, in _acquire_with_cache_info
    file = self._cache[self._key]
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/lru_cache.py", line 56, in __getitem__
    value = self._cache[key]
KeyError: [<class 'netCDF4._netCDF4.Dataset'>, ('/home/cdalden/summa_setup/model/forcings/grandtarghee_+4K_WY02.nc',), 'r', (('clobber', True), ('diskless', False), ('format', 'NETCDF4'), ('persist', False)), 'bd6041a9-0b8e-43d2-877d-0fed09e5f057']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cdalden/summa_setup/model/run_summa_stats.py", line 28, in <module>
    forcing = xr.open_dataset('./forcings/'+forcing_file.strip(), engine='netcdf4')
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/api.py", line 570, in open_dataset
    backend_ds = backend.open_dataset(
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 602, in open_dataset
    store = NetCDF4DataStore.open(
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 400, in open
    return cls(manager, group=group, mode=mode, lock=lock, autoclose=autoclose)
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 347, in __init__
    self.format = self.ds.data_model
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 409, in ds
    return self._acquire()
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 403, in _acquire
    with self._manager.acquire_context(needs_lock) as root:
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/file_manager.py", line 199, in acquire_context
    file, cached = self._acquire_with_cache_info(needs_lock)
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/file_manager.py", line 217, in _acquire_with_cache_info
    file = self._opener(*self._args, **kwargs)
  File "src/netCDF4/_netCDF4.pyx", line 2330, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 1948, in netCDF4._netCDF4._ensure_nc_success
FileNotFoundError: [Errno 2] No such file or directory: b'/home/cdalden/summa_setup/model/forcings/grandtarghee_+4K_WY02.nc'
summa run for grandtarghee_+4K_WY02 complete, check output folder for output file
Enter the desired SNOTEL site code (ie. 1107:WA): Enter the water year: Enter the output file name (ie. buck_WY16): No ACCUMULATED PRECIPITATION found for MyStation
No AIR TEMP found for MyStation
No SWE found for MyStation
No SNOWDEPTH found for MyStation
********** generating the forcing file, please be patient **********
********** should take ~3 minutes to run **********
Traceback (most recent call last):
  File "/home/cdalden/summa_setup/model/snotel_to_pysumma_+4K.py", line 112, in <module>
    df.reset_index(inplace=True)
AttributeError: 'NoneType' object has no attribute 'reset_index'
forcing file created, now running summa
Traceback (most recent call last):
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/file_manager.py", line 211, in _acquire_with_cache_info
    file = self._cache[self._key]
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/lru_cache.py", line 56, in __getitem__
    value = self._cache[key]
KeyError: [<class 'netCDF4._netCDF4.Dataset'>, ('/home/cdalden/summa_setup/model/forcings/grandtarghee_+4K_WY03.nc',), 'r', (('clobber', True), ('diskless', False), ('format', 'NETCDF4'), ('persist', False)), 'b0bb28eb-c287-4f09-b967-81ffeea4a601']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cdalden/summa_setup/model/run_summa_stats.py", line 28, in <module>
    forcing = xr.open_dataset('./forcings/'+forcing_file.strip(), engine='netcdf4')
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/api.py", line 570, in open_dataset
    backend_ds = backend.open_dataset(
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 602, in open_dataset
    store = NetCDF4DataStore.open(
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 400, in open
    return cls(manager, group=group, mode=mode, lock=lock, autoclose=autoclose)
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 347, in __init__
    self.format = self.ds.data_model
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 409, in ds
    return self._acquire()
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 403, in _acquire
    with self._manager.acquire_context(needs_lock) as root:
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/file_manager.py", line 199, in acquire_context
    file, cached = self._acquire_with_cache_info(needs_lock)
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/file_manager.py", line 217, in _acquire_with_cache_info
    file = self._opener(*self._args, **kwargs)
  File "src/netCDF4/_netCDF4.pyx", line 2330, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 1948, in netCDF4._netCDF4._ensure_nc_success
FileNotFoundError: [Errno 2] No such file or directory: b'/home/cdalden/summa_setup/model/forcings/grandtarghee_+4K_WY03.nc'
summa run for grandtarghee_+4K_WY03 complete, check output folder for output file
Enter the desired SNOTEL site code (ie. 1107:WA): Enter the water year: Enter the output file name (ie. buck_WY16): No ACCUMULATED PRECIPITATION found for MyStation
No AIR TEMP found for MyStation
No SWE found for MyStation
No SNOWDEPTH found for MyStation
********** generating the forcing file, please be patient **********
********** should take ~3 minutes to run **********
Traceback (most recent call last):
  File "/home/cdalden/summa_setup/model/snotel_to_pysumma_+4K.py", line 112, in <module>
    df.reset_index(inplace=True)
AttributeError: 'NoneType' object has no attribute 'reset_index'
forcing file created, now running summa
Traceback (most recent call last):
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/file_manager.py", line 211, in _acquire_with_cache_info
    file = self._cache[self._key]
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/lru_cache.py", line 56, in __getitem__
    value = self._cache[key]
KeyError: [<class 'netCDF4._netCDF4.Dataset'>, ('/home/cdalden/summa_setup/model/forcings/grandtarghee_+4K_WY04.nc',), 'r', (('clobber', True), ('diskless', False), ('format', 'NETCDF4'), ('persist', False)), 'ac7c3d18-c09a-466e-98c4-721ea2691ae8']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cdalden/summa_setup/model/run_summa_stats.py", line 28, in <module>
    forcing = xr.open_dataset('./forcings/'+forcing_file.strip(), engine='netcdf4')
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/api.py", line 570, in open_dataset
    backend_ds = backend.open_dataset(
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 602, in open_dataset
    store = NetCDF4DataStore.open(
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 400, in open
    return cls(manager, group=group, mode=mode, lock=lock, autoclose=autoclose)
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 347, in __init__
    self.format = self.ds.data_model
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 409, in ds
    return self._acquire()
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 403, in _acquire
    with self._manager.acquire_context(needs_lock) as root:
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/file_manager.py", line 199, in acquire_context
    file, cached = self._acquire_with_cache_info(needs_lock)
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/file_manager.py", line 217, in _acquire_with_cache_info
    file = self._opener(*self._args, **kwargs)
  File "src/netCDF4/_netCDF4.pyx", line 2330, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 1948, in netCDF4._netCDF4._ensure_nc_success
FileNotFoundError: [Errno 2] No such file or directory: b'/home/cdalden/summa_setup/model/forcings/grandtarghee_+4K_WY04.nc'
summa run for grandtarghee_+4K_WY04 complete, check output folder for output file
Enter the desired SNOTEL site code (ie. 1107:WA): Enter the water year: Enter the output file name (ie. buck_WY16): No ACCUMULATED PRECIPITATION found for MyStation
No AIR TEMP found for MyStation
No SWE found for MyStation
No SNOWDEPTH found for MyStation
********** generating the forcing file, please be patient **********
********** should take ~3 minutes to run **********
Traceback (most recent call last):
  File "/home/cdalden/summa_setup/model/snotel_to_pysumma_+4K.py", line 112, in <module>
    df.reset_index(inplace=True)
AttributeError: 'NoneType' object has no attribute 'reset_index'
forcing file created, now running summa
Traceback (most recent call last):
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/file_manager.py", line 211, in _acquire_with_cache_info
    file = self._cache[self._key]
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/lru_cache.py", line 56, in __getitem__
    value = self._cache[key]
KeyError: [<class 'netCDF4._netCDF4.Dataset'>, ('/home/cdalden/summa_setup/model/forcings/grandtarghee_+4K_WY05.nc',), 'r', (('clobber', True), ('diskless', False), ('format', 'NETCDF4'), ('persist', False)), 'e284c3eb-183f-49dc-aec9-d561b231d6bc']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cdalden/summa_setup/model/run_summa_stats.py", line 28, in <module>
    forcing = xr.open_dataset('./forcings/'+forcing_file.strip(), engine='netcdf4')
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/api.py", line 570, in open_dataset
    backend_ds = backend.open_dataset(
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 602, in open_dataset
    store = NetCDF4DataStore.open(
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 400, in open
    return cls(manager, group=group, mode=mode, lock=lock, autoclose=autoclose)
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 347, in __init__
    self.format = self.ds.data_model
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 409, in ds
    return self._acquire()
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 403, in _acquire
    with self._manager.acquire_context(needs_lock) as root:
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/file_manager.py", line 199, in acquire_context
    file, cached = self._acquire_with_cache_info(needs_lock)
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/file_manager.py", line 217, in _acquire_with_cache_info
    file = self._opener(*self._args, **kwargs)
  File "src/netCDF4/_netCDF4.pyx", line 2330, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 1948, in netCDF4._netCDF4._ensure_nc_success
FileNotFoundError: [Errno 2] No such file or directory: b'/home/cdalden/summa_setup/model/forcings/grandtarghee_+4K_WY05.nc'
summa run for grandtarghee_+4K_WY05 complete, check output folder for output file
Enter the desired SNOTEL site code (ie. 1107:WA): Enter the water year: Enter the output file name (ie. buck_WY16): ********** generating the forcing file, please be patient **********
********** should take ~3 minutes to run **********
Traceback (most recent call last):
  File "/home/cdalden/summa_setup/model/snotel_to_pysumma_+4K.py", line 241, in <module>
    met_data['prec'].values[:, 0, 0] = prec_vals
ValueError: could not broadcast input array from shape (37,) into shape (365,)
forcing file created, now running summa
Traceback (most recent call last):
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/file_manager.py", line 211, in _acquire_with_cache_info
    file = self._cache[self._key]
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/lru_cache.py", line 56, in __getitem__
    value = self._cache[key]
KeyError: [<class 'netCDF4._netCDF4.Dataset'>, ('/home/cdalden/summa_setup/model/forcings/grandtarghee_+4K_WY06.nc',), 'r', (('clobber', True), ('diskless', False), ('format', 'NETCDF4'), ('persist', False)), 'e9de9c34-ca5e-4d69-8c87-eff72d6863bc']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cdalden/summa_setup/model/run_summa_stats.py", line 28, in <module>
    forcing = xr.open_dataset('./forcings/'+forcing_file.strip(), engine='netcdf4')
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/api.py", line 570, in open_dataset
    backend_ds = backend.open_dataset(
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 602, in open_dataset
    store = NetCDF4DataStore.open(
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 400, in open
    return cls(manager, group=group, mode=mode, lock=lock, autoclose=autoclose)
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 347, in __init__
    self.format = self.ds.data_model
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 409, in ds
    return self._acquire()
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 403, in _acquire
    with self._manager.acquire_context(needs_lock) as root:
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/file_manager.py", line 199, in acquire_context
    file, cached = self._acquire_with_cache_info(needs_lock)
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/file_manager.py", line 217, in _acquire_with_cache_info
    file = self._opener(*self._args, **kwargs)
  File "src/netCDF4/_netCDF4.pyx", line 2330, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 1948, in netCDF4._netCDF4._ensure_nc_success
FileNotFoundError: [Errno 2] No such file or directory: b'/home/cdalden/summa_setup/model/forcings/grandtarghee_+4K_WY06.nc'
summa run for grandtarghee_+4K_WY06 complete, check output folder for output file
Enter the desired SNOTEL site code (ie. 1107:WA): Enter the water year: Enter the output file name (ie. buck_WY16): ********** generating the forcing file, please be patient **********
********** should take ~3 minutes to run **********
Traceback (most recent call last):
  File "/home/cdalden/summa_setup/model/snotel_to_pysumma_+4K.py", line 287, in <module>
    state['prec'].values[:, 0, 0] = prec_vals
ValueError: could not broadcast input array from shape (37,) into shape (90,)
forcing file created, now running summa
Traceback (most recent call last):
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/file_manager.py", line 211, in _acquire_with_cache_info
    file = self._cache[self._key]
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/lru_cache.py", line 56, in __getitem__
    value = self._cache[key]
KeyError: [<class 'netCDF4._netCDF4.Dataset'>, ('/home/cdalden/summa_setup/model/forcings/grandtarghee_+4K_WY07.nc',), 'r', (('clobber', True), ('diskless', False), ('format', 'NETCDF4'), ('persist', False)), '4eb9e5db-acde-478b-8db4-a01ce71a25bf']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cdalden/summa_setup/model/run_summa_stats.py", line 28, in <module>
    forcing = xr.open_dataset('./forcings/'+forcing_file.strip(), engine='netcdf4')
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/api.py", line 570, in open_dataset
    backend_ds = backend.open_dataset(
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 602, in open_dataset
    store = NetCDF4DataStore.open(
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 400, in open
    return cls(manager, group=group, mode=mode, lock=lock, autoclose=autoclose)
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 347, in __init__
    self.format = self.ds.data_model
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 409, in ds
    return self._acquire()
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 403, in _acquire
    with self._manager.acquire_context(needs_lock) as root:
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/file_manager.py", line 199, in acquire_context
    file, cached = self._acquire_with_cache_info(needs_lock)
  File "/home/cdalden/miniforge3/envs/pysumma/lib/python3.9/site-packages/xarray/backends/file_manager.py", line 217, in _acquire_with_cache_info
    file = self._opener(*self._args, **kwargs)
  File "src/netCDF4/_netCDF4.pyx", line 2330, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 1948, in netCDF4._netCDF4._ensure_nc_success
FileNotFoundError: [Errno 2] No such file or directory: b'/home/cdalden/summa_setup/model/forcings/grandtarghee_+4K_WY07.nc'
summa run for grandtarghee_+4K_WY07 complete, check output folder for output file
Enter the desired SNOTEL site code (ie. 1107:WA): Enter the water year: Enter the output file name (ie. buck_WY16): ********** generating the forcing file, please be patient **********
********** should take ~3 minutes to run **********
forcing file created, now running summa
Model status: Success
number of crust days:59.166666666666664
summa run for grandtarghee_+4K_WY08 complete, check output folder for output file
Enter the desired SNOTEL site code (ie. 1107:WA): Enter the water year: Enter the output file name (ie. buck_WY16): ********** generating the forcing file, please be patient **********
********** should take ~3 minutes to run **********
forcing file created, now running summa
Model status: Success
number of crust days:72.29166666666667
summa run for grandtarghee_+4K_WY09 complete, check output folder for output file
Enter the desired SNOTEL site code (ie. 1107:WA): Enter the water year: Enter the output file name (ie. buck_WY16): ********** generating the forcing file, please be patient **********
********** should take ~3 minutes to run **********
forcing file created, now running summa
Model status: Success
number of crust days:84.79166666666667
summa run for grandtarghee_+4K_WY10 complete, check output folder for output file
Enter the desired SNOTEL site code (ie. 1107:WA): Enter the water year: Enter the output file name (ie. buck_WY16): ********** generating the forcing file, please be patient **********
********** should take ~3 minutes to run **********
forcing file created, now running summa
Model status: Success
number of crust days:26.666666666666668
summa run for grandtarghee_+4K_WY11 complete, check output folder for output file
Enter the desired SNOTEL site code (ie. 1107:WA): Enter the water year: Enter the output file name (ie. buck_WY16): ********** generating the forcing file, please be patient **********
********** should take ~3 minutes to run **********
forcing file created, now running summa
Model status: Success
number of crust days:43.333333333333336
summa run for grandtarghee_+4K_WY12 complete, check output folder for output file
Enter the desired SNOTEL site code (ie. 1107:WA): Enter the water year: Enter the output file name (ie. buck_WY16): ********** generating the forcing file, please be patient **********
********** should take ~3 minutes to run **********
forcing file created, now running summa
Model status: Success
number of crust days:43.583333333333336
summa run for grandtarghee_+4K_WY13 complete, check output folder for output file
Enter the desired SNOTEL site code (ie. 1107:WA): Enter the water year: Enter the output file name (ie. buck_WY16): ********** generating the forcing file, please be patient **********
********** should take ~3 minutes to run **********
forcing file created, now running summa
Model status: Success
number of crust days:48.458333333333336
summa run for grandtarghee_+4K_WY14 complete, check output folder for output file
Enter the desired SNOTEL site code (ie. 1107:WA): Enter the water year: Enter the output file name (ie. buck_WY16): ********** generating the forcing file, please be patient **********
********** should take ~3 minutes to run **********
forcing file created, now running summa
Model status: Success
number of crust days:70.66666666666667
summa run for grandtarghee_+4K_WY15 complete, check output folder for output file
Enter the desired SNOTEL site code (ie. 1107:WA): Enter the water year: Enter the output file name (ie. buck_WY16): ********** generating the forcing file, please be patient **********
********** should take ~3 minutes to run **********
forcing file created, now running summa
Model status: Success
number of crust days:20.0
summa run for grandtarghee_+4K_WY16 complete, check output folder for output file
Enter the desired SNOTEL site code (ie. 1107:WA): Enter the water year: Enter the output file name (ie. buck_WY16): ********** generating the forcing file, please be patient **********
********** should take ~3 minutes to run **********
forcing file created, now running summa
Model status: Success
number of crust days:41.666666666666664
summa run for grandtarghee_+4K_WY17 complete, check output folder for output file
Enter the desired SNOTEL site code (ie. 1107:WA): Enter the water year: Enter the output file name (ie. buck_WY16): ********** generating the forcing file, please be patient **********
********** should take ~3 minutes to run **********
forcing file created, now running summa
Model status: Success
number of crust days:43.916666666666664
summa run for grandtarghee_+4K_WY18 complete, check output folder for output file
Enter the desired SNOTEL site code (ie. 1107:WA): Enter the water year: Enter the output file name (ie. buck_WY16): ********** generating the forcing file, please be patient **********
********** should take ~3 minutes to run **********
forcing file created, now running summa
Model status: Success
number of crust days:22.083333333333332
summa run for grandtarghee_+4K_WY19 complete, check output folder for output file
Enter the desired SNOTEL site code (ie. 1107:WA): Enter the water year: Enter the output file name (ie. buck_WY16): ********** generating the forcing file, please be patient **********
********** should take ~3 minutes to run **********
forcing file created, now running summa
Model status: Success
number of crust days:35.541666666666664
summa run for grandtarghee_+4K_WY20 complete, check output folder for output file
Enter the desired SNOTEL site code (ie. 1107:WA): Enter the water year: Enter the output file name (ie. buck_WY16): ********** generating the forcing file, please be patient **********
********** should take ~3 minutes to run **********
forcing file created, now running summa
Model status: Success
number of crust days:99.91666666666667
summa run for grandtarghee_+4K_WY21 complete, check output folder for output file
Enter the desired SNOTEL site code (ie. 1107:WA): Enter the water year: Enter the output file name (ie. buck_WY16): ********** generating the forcing file, please be patient **********
********** should take ~3 minutes to run **********
forcing file created, now running summa
Model status: Success
number of crust days:64.08333333333333
summa run for grandtarghee_+4K_WY22 complete, check output folder for output file
Enter the desired SNOTEL site code (ie. 1107:WA): Enter the water year: Enter the output file name (ie. buck_WY16): ********** generating the forcing file, please be patient **********
********** should take ~3 minutes to run **********
forcing file created, now running summa
Model status: Success
number of crust days:44.083333333333336
summa run for grandtarghee_+4K_WY23 complete, check output folder for output file
Enter the desired SNOTEL site code (ie. 1107:WA): Enter the water year: Enter the output file name (ie. buck_WY16): ********** generating the forcing file, please be patient **********
********** should take ~3 minutes to run **********
forcing file created, now running summa
Model status: Success
number of crust days:70.95833333333333
summa run for grandtarghee_+4K_WY24 complete, check output folder for output file
